# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTemplateLibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
    ]
